typeidea/typeidea/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path


from blog.views import post_list, PostDetailView, IndexView, CategoryView, TagView, SearchView, AuthorView
from config.views import LinkListView
from comment.views import CommentView
from typeidea.custom_site import custom_site

urlpatterns = [
    re_path(r'^$', IndexView.as_view(), name='index'),
    re_path(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
    re_path(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view(), name='tag-list'),
    re_path(r'^post/(?P<pk>\d+)$', PostDetailView.as_view(), name='post-detail'),
    re_path(r'^links/$', LinkListView.as_view(), name='links'),
    re_path(r'^super_admin/', admin.site.urls, name='super-admin'),
    re_path(r'^admin/', custom_site.urls, name='admin'),
    re_path(r'^search/$', SearchView.as_view(), name='search'),
    re_path(r'^author/(?P<owner_id>\d+)/$', AuthorView.as_view(), name='author'),
    re_path(r'^comment/$', CommentView.as_view(), name='comment'),
]

typeidea/comment/models.py
from django.db import models

from blog.models import Post


# Create your models here.


class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '刪除'),
    )

    target = models.CharField(max_length=100, verbose_name="評論目標")
    content = models.CharField(max_length=2000, verbose_name="內容")
    nickname = models.CharField(max_length=50, verbose_name="昵稱")
    website = models.URLField(verbose_name="網站")
    email = models.EmailField(verbose_name="郵箱")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="狀態")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="創建時間")

    def __str__(self):
        return self.target

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

    class Meta:
        verbose_name = "評論"
        verbose_name_plural = verbose_name
        db_table = 'Comment'

typeidea/config/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.loader import render_to_string


# Create your models here.

class Link(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '刪除'),
    )

    title = models.CharField(max_length=255, verbose_name="標題")
    href = models.URLField(verbose_name="鏈接")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="狀態")
    weight = models.PositiveIntegerField(default=1, choices=zip(range(1, 6), range(1, 6)), verbose_name="權重",
                                         help_text="權重高展示順序靠前")
    owner = models.ForeignKey(User, verbose_name="作者", on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="創建時間")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "友鏈"
        verbose_name_plural = verbose_name
        db_table = 'Link'


class SideBar(models.Model):
    DISPLAY_HTML = 1
    DISPLAY_LATEST = 2
    DISPLAY_HOT = 3
    DISPLAY_COMMENT = 4
    SIDE_TYPE = {
        (DISPLAY_HTML, 'HTML'),
        (DISPLAY_LATEST, '最新文章'),
        (DISPLAY_HOT, '最熱文章'),
        (DISPLAY_COMMENT, '最近評論'),
    }

    STATUS_SHOW = 1
    STATUS_HIDE = 0
    STATUS_ITEMS = (
        (STATUS_SHOW, '展示'),
        (STATUS_HIDE, '隱藏'),
    )

    title = models.CharField(max_length=255, verbose_name="標題")
    display_type = models.PositiveIntegerField(default=1, choices=SIDE_TYPE, verbose_name="展示類型")
    content = models.CharField(max_length=500, blank=True, verbose_name="內容", help_text="如果設置的不是HTML類型，可爲空")
    status = models.PositiveIntegerField(default=STATUS_SHOW, choices=STATUS_ITEMS, verbose_name="狀態")
    owner = models.ForeignKey(User, verbose_name="作者", on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="創建時間")

    def __str__(self):
        return self.title

    @classmethod
    def get_all(cls):
        return cls.objects.filter(status=cls.STATUS_SHOW)

    @property
    def content_html(self):
        """直接渲染模板"""
        from blog.models import Post    # 避免循環引用
        from comment.models import Comment

        result = ''
        if self.display_type == self.DISPLAY_HTML:
            result = self.content
        elif self.display_type == self.DISPLAY_LATEST:
            content = {
                'posts': Post.latest_posts()
            }
            result = render_to_string('config/blocks/sidebar_posts.html', content)
        elif self.display_type == self.DISPLAY_HOT:
            content = {
                'posts': Post.hot_posts()
            }
            result = render_to_string('config/blocks/sidebar_posts.html', content)
        elif self.display_type == self.DISPLAY_COMMENT:
            content = {
                'comments': Comment.objects.filter(status=Comment.STATUS_NORMAL)
            }
            result = render_to_string('config/blocks/sidebar_comments.html', content)
        return result

    class Meta:
        verbose_name = "側邊欄 "
        verbose_name_plural = verbose_name
        db_table = 'SideBar'

typeidea/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} 首頁 {% endblock %} - typeidea博客系統</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.css">
    <style>
        .post {
            margin-bottom: 5px;
        {#配置每個post卡片下面的間隔#}
        }
    </style>
{% block extra_head %}
{% endblock %}
</head>
<body>
<div class="container head">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">首頁</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% for cate in navs %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category-list' cate.id %}">
                            {{ cate.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
            <form class="form-inline my-2 my-lg-0" action='/search/' method="GET">
                <input class="form-control mr-sm-2" type="search" name="keyword" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">搜索</button>
            </form>
        </div>
    </nav>
    <div class="jumbotron">
        <h1 class="display-4">Typeidea</h1>
        <p class="lead">基於Django的多人博客系統</p>
    </div>
</div>

<div class="container main">
    <div class="row">
        <div class="col-9 post-list">
            {% block main %}
            {% endblock %}
        </div>
        <div class="col-3">
            {% block sidebar %}
                {% for sidebar in sidebars %}
                    <div class="card sidebar">
                        <div class="card-body">
                            <h4 class="card-title">{{ sidebar.title }}</h4>
                            <p>
                                {{ sidebar.content_html }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>

<footer class="footer">
    {% block footer %}
        <div class="container">
            <hr/>
            <nav class="nav category">
                {% for cate in categories %}
                    <a href="{% url 'category-list' cate.id %}" class="nav-link">
                        {{ cate.name }}
                    </a>
                {% endfor %}
            </nav>
        </div>
        <div class="container power">
            <span class="text-muted">Power by @Alroy</span>
        </div>
    {% endblock %}
</footer>

</body>
</html>

typeidea/templates/block.html
{% extends 'base.html' %}
{% load comment_block %}
{% block title %} post.title {% endblock %}

{% block main %}
    <hr/>
    <div class="comment">
        <form class="form-group" action="/comment/" method="POST">
            {% csrf_token %}
            <input name="target" type="hidden" value="{{ target }}"/>
            {{ comment_form }}
            <input type="submit" value="寫好了!"/>
        </form>

        <!--評論列表-->
        <ul class="list-group">
            {% for comment in comment_list %}
                <li class="list-group-item">
                    <div class="nickname">
                        <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                        <span>{{ comment.created_time }}</span>
                    </div>
                    <div class="comment-context">
                        {% autoescape off %}
                        {{ comment.content }}
                        {% endautoescape %}
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

typeidea/templates/detail.html
{% extends 'base.html' %}

{% block title %} post.title {% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="https://cdn.bootcss.com/highlight.js/9.12.0/styles/googlecode.min.css">
    <script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block main %}
    {% if post %}
        <h1>{{ post.title }}</h1>
        <div>
            <span>分類:{{ post.category.name }}</span>
            <span>作者:{{ post.owner.username }}</span>
        </div>
        <hr/>
        <p>
            {{ post.content }}
        </p>
    {% endif %}

    <hr/>
    <div  class="comment">
        <form class="form-group" action="/comment/" method="POST">
            {% csrf_token %}
            <input name="target" type="hidden" value="{{ request.path }}"/>
            {{ comment_form }}
            <input type="submit" value="寫好了!"/>
        </form>

        <!--評論列表-->
        <ul class="list-group">
            {% for comment in comment_list %}
                <li class="list-group-item">
                    <div class="nickname">
                        <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                        <span>{{ comment.created_time }}</span>
                    </div>
                    <div class="comment-context">
                        {% autoescape off %}
                        {{ comment.content }}
                        {% endautoescape %}
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}

typeidea/templates/links.html
{% extends 'base.html' %}
{% block title %}友情鏈接{% endblock %}

{% block main %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">名稱</th>
            <th scope="col">網址</th>
        </tr>
        </thead>
        <tbody>
        {% for link in link_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ link.title }}</td>
                <td><a href="{{ link.href }}">{{ link.href }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

typeidea/templates/list.html
{% extends "base.html" %}
{% block title %}
    {% if tag %}
        標籤頁:{{ tag.name }}
    {% elif category %}
        分類頁:{{ category.name }}
    {% else %}
        首頁
    {% endif %}
{% endblock %}


{% block main %}
    {% for post in post_list %}
        <div class="card post">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h5>
                <span class="card-link">作者:<a href="#">{{ post.owner.username }}</a></span>
                <span class="card-link">分類:<a
                        href="{% url 'category-list' post.category.id %}">{{ post.category.name }}</a></span>
                <span class="card-link">標籤:
                    {% for tag in post.tag.all %}
                        <a href="{% url 'tag-list' tag.id %}">{{ tag.name }}</a>
                    {% endfor %}
                    </span>
                <p class="card-list">{{ post.desc }}<a href="{% url 'post-detail' post.id %}">完整內容</a></p>
            </div>
        </div>
    {% endfor %}

    {% if page_obj %}
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一頁</a>
        {% endif %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一頁 </a>
        {% endif %}
    {% endif %}
{% endblock %}

typeidea/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>評論結果頁</title>
    <style>
        body {
            TEXT-ALIGN: center;
        }

        .results {
            text-align: center;
            width: 40%;
            margin: auto;
        }

        .errorlist {
            color: red;
        }

        ul li {
            list-style-type: None;
        }
    </style>
</head>
<body>
<div class="errorlist">
    {% if succeed %}
        評論成功!
        <a href="{{ target }}"></a>
    {% else %}
        <ul class="errorlist">
            {% for field, message in form.errors.items %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        <a href="javascript:window.history.back();">返回</a>
    {% endif %}
</div>
</body>
</html>